{{- if .Values.rbac.create }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ default "Role" .Values.rbac.roleKind }}
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    appVersion: "{{ .Values.appVersion }}"
{{- if .Values.rbac.rules }}
rules:
  {{- .Values.rbac.rules | nindent 2 }}
{{- else }}
rules: []
{{- end }}

---
kind: {{ default "RoleBinding" .Values.rbac.roleBindingKind }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    appVersion: "{{ .Values.appVersion }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ default "Role" .Values.rbac.roleKind }}
  name: {{ template "fullname" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
